import datajoint as dj

from dj_config import start_connection
dbname = start_connection()
schema = dj.schema(dbname, locals())

@schema
class Mice(dj.Manual):
    definition = """
    # Mouse table lists all the mice used and the relevant attributes
      mouse_id: varchar(128)                        # unique mouse id
      ---
      strain:   varchar(128)                        # genetic strain
      dob: varchar(128)                             # mouse date of birth 
      sex: enum('M', 'F', 'U')                      # sex of mouse - Male, Female, or Unknown/Unclassified
      single_housed: enum('Y', 'N')                 # single housed or group caged
      enriched_cage: enum('Y', 'N')                 # presence of wheel or other stuff in the cage
    """

@schema
class Sessions(dj.Manual):
    definition = """
    # A session is one behavioural experiment performed on one mouse on one day
    uid: smallint     # unique number that defines each session
    name: varchar(128)  # unique name that defines each session - YYMMDD_MOUSEID
    ---
    -> Mice
    date: date             # date in the YYYY-MM-DD format
    num_recordings: smallint   # number of recordings performed within that session
    experiment_name: varchar(128)  # name of the experiment the session is part of 
    experimenter: varchar(128)      # name of the person performing the experiment
    """

@schema
class Recordings(dj.Manual):
    definition = """
    # Within one session one may perform several recordings. Each recording has its own video and metadata files
    recording_uid: varchar(128)   # uniquely identifying name for each recording YYMMDD_MOUSEID_RECNUM
    ---
    -> Sessions
    rec_num: smallint       # recording number within that session
    video_file_path: varchar(128) # path to the file storing the video data
    video_format: enum('tdms', 'avi', 'mp4')  # format in which the video was recorded
    converted_video_file_path: varchar(128)  # if video was recorded in.tdms and converted to video,where is the video stored
    metadata_file_path: varchar(128) # path to the .tdms file storing the metadata
    pose_data: varchar(128)   # path to .h5 data file generated by dlc
    """

@schema
class Trials(dj.Imported):
    definition = """
    # Metadata of each trial (e.g. stim type and frame of onset)
    -> Recordings
    uid: varchar(128)  # uniquely identifuing ID for each trial YYMMDD_MOUSEID_RECNUM_TRIALNUM
    ---
    stim_type: varchar(128)
    stim_start: int   # number of frame at start of stim
    stim_duration: int   # duration in frames
    """


